version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:3000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_auth
      MYSQL_USER: nest_auth
      MYSQL_PASSWORD: nest_auth
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '33066:3306'
